---
title: "Compras governamentais"
author: "Fernando Almeida Barbalho"
date: '2024-01-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)

dca_despesa_orcamentaria_2022 <- readRDS("dca_despesa_orcamentaria_2022.RDS")
licitacao <- readRDS("licitacao.rds")


```

```{r}
dca_despesa_orcamentaria_2022 %>%
  filter(cod_conta %in% c("DO3.3.90.30.00.00",
                          "DO3.3.90.32.00.00",
                          "DO3.3.90.33.00.00",
                          "DO3.3.90.35.00.00",
                          "DO3.3.90.36.00.00",
                          "DO3.3.90.39.00.00",
                          "DO3.3.90.38.00.00",
                          "DO3.3.90.37.00.00",
                          "DO4.4.90.51.00.00",
                          "DO4.4.90.52.00.00")) %>%
  mutate(conta = str_sub(conta,16,200)) %>%
  filter(coluna == "Despesas Liquidadas") %>%
  mutate(tipo_despesa = ifelse(substr(cod_conta,1,3)=="DO3","Custeio","Bens de capital")) %>%
  mutate(conta = reorder(conta, valor)) %>%
  arrange(desc(valor)) %>%
  ggplot(aes(x=valor, y=conta)) +
  geom_col(aes(fill= tipo_despesa)) +
  geom_text( aes(label= round(valor/10^9,1)),hjust=c(1,1,rep(-0.1,7)), size=3)+
  theme_light() +
  theme(
    panel.grid = element_blank(),
    panel.border = element_blank(),
    axis.text.x = element_blank()
  ) +
  labs(
    title = "Compras governamentais dos órgãos OFSS",
    subtitle = "Valores liquidados em R$bi para 2022",
    caption = "Fonte: SICONFI. Elaboração própria",
    fill= "Tipo de compra",
    x = "",
    y = ""
  )
  
  
```

```{r}

licitacao %>%
  filter(situacao_licitacao == "Encerrado",
         uf != "-3") %>% 
  summarise( valor = sum(valor_licitacao),
             .by = uf) %>%
  ungroup() %>%
  mutate(uf= reorder(uf,valor)) %>%
  arrange(desc(valor)) %>%
  ggplot(aes(x=valor, y= uf )) +
  geom_col(fill= "black")+
  geom_text( aes(label= round(valor/10^6,1)),
             hjust=c(1,rep(-0.1,26)),
             color= c("white", rep("black",26)),
             size=3)+
  theme_light() +
  theme(
    panel.grid = element_blank(),
    panel.border = element_blank(),
    axis.text.x = element_blank()
  ) +
  labs(
    title = "Soma de valores licitados por estado",
    subtitle = "Valores em R$mi entre dez-22 e nov-23",
    caption = "Fonte: Portal da Transparência. Elaboração própria",
    x = "",
    y = ""
  )

```

